version: '3.9'

services:
  app:
    container_name: dad_app
    build:
      context: .
    command:

      sh -c "PYTHONPATH=.
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./dad:/dad
    environment:
      - DB_HOST=db
      - DB_NAME=dand_app
      - DB_USER=root
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dand_app
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306