services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
      - ./scripts/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_HOST: 'localhost'
      MYSQL_PORT: '3306'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'zai'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:8000'
    volumes:
      - ./dad:/dad
    depends_on:
      - db