# Generated by Django 3.2 on 2022-03-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('l', 'light'), ('m', 'medium'), ('h', 'heavy')], default='l', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mage', 'mage'), ('ranger', 'ranger'), ('warrior', 'warrior')], max_length=15)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.armor')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('oneH', '1-handed'), ('twoH', '2-handed'), ('dual', 'dual wield'), ('lBow', 'long bow'), ('sBow', 'short bow'), ('wand', 'magic wand'), ('scepter', 'magic scepter'), ('mSward', 'magic sword')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('level', models.IntegerField(default=1)),
                ('character_preset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='characters.preset')),
            ],
        ),
        migrations.AddField(
            model_name='preset',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.weapon'),
        ),
    ]
