# Generated by Django 3.2 on 2022-03-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='weapon',
        ),
        migrations.AddField(
            model_name='preset',
            name='weapon',
            field=models.ManyToManyField(to='characters.Weapon'),
        ),
    ]
