# Generated by Django 3.2 on 2022-03-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20220310_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='name',
            field=models.CharField(choices=[('light', 'l'), ('medium', 'm'), ('heavy', 'h')], default='l', max_length=8),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(choices=[('1-handed', 'oneH'), ('2-handed', 'twoH'), ('dual wield', 'dual'), ('long bow', 'lBow'), ('short bow', 'sBow'), ('magic wand', 'wand'), ('magic scepter', 'scepter'), ('magic sword', 'mSward')], max_length=15),
        ),
    ]
