# Generated by Django 3.2 on 2022-03-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20220310_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='name',
            field=models.CharField(choices=[('l', 'light'), ('m', 'medium'), ('h', 'heavy')], default='l', max_length=2),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(choices=[('oneH', '1-handed'), ('twoH', '2-handed'), ('dual', 'dual wield'), ('lBow', 'long bow'), ('sBow', 'short bow'), ('wand', 'magic wand'), ('scepter', 'magic scepter'), ('mSward', 'magic sword')], max_length=10),
        ),
    ]
