# Generated by Django 3.2 on 2022-03-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_weapon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
