# Generated by Django 3.2 on 2022-03-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_preset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(choices=[('1-handed', 'oneH'), ('2-handed', 'twoH'), ('dual wield', 'dual'), ('long bow', 'lBow'), ('short bow', 'sBow'), ('magic wand', 'wand'), ('magic scepter', 'scepter'), ('magic sword', 'mSward')], max_length=20),
        ),
    ]
