# Generated by Django 3.2 on 2022-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_weapon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(choices=[('1-handed', '1-handed'), ('2-handed', '2-handed'), ('dual wield', 'dual wield'), ('long bow', 'long bow'), ('short bow', 'short bow'), ('magic wand', 'magic wand'), ('magic scepter', 'magic scepter'), ('magic sword', 'magic sword')], max_length=20),
        ),
    ]
