# Generated by Django 3.2 on 2022-03-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_alter_weapon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='name',
            field=models.CharField(choices=[('light', 'light'), ('medium', 'medium'), ('heavy', 'heavy')], default='l', max_length=10),
        ),
    ]
